### ISSUE TITLE
DNS patch to KFS APIs (Abstraction)

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#10]
1. DNS Entry
2. Forwarding
3. Latency & Optimizations

**Comment by kggp1995** [comment]
@ayushgupta0610 will help at UI level

**Comment by Chandra-Aicumen** [comment]
@0zAND1z , moving to inbox for backlog review.

**Comment by 0zAND1z** [comment]
@Chandra-Aicumen , seconded, I believe that we can achieve DNS once Kuberenetes & API code refactoring is finished.

**Comment by 0zAND1z** [comment]
This has been achieved and tested during WyoHackathon. Closing the thread.

Thanks to all involved.
