### ISSUE TITLE
Eliminate appending entry into explorer in De-Duplication

### ISSUE THREAD

**Issue by its-VSP** [KIPFoundation/kfs#101]
When de-duplication context is getting triggered,  file should not be appended to user's explorer.

**Comment by its-VSP** [comment]
So @0zAND1z @akshitababel 
When this de-duplication is  triggered , client is to be notified with API response.
 Response : 
 status : 200 (OK)
Message : "File already exists"

What you say?

**Comment by Chandra-Aicumen** [comment]
@0zAND1z , code is in the repo and almost a month.  When can we move to master

**Comment by 0zAND1z** [comment]
Hi @Chandra-Aicumen , Work item 101 has been addressed under two commits c9963d13 & 541891af.

Both commits were made on 6th of MAR, and fall under the span of current BETA-4 sprint.

So, review is not delayed in this case. We can take it up today.
