### ISSUE TITLE
Single Entry for Upload File

### ISSUE THREAD

**Issue by mosinms7711** [KIPFoundation/kfs#102]
When sender and receiver is same, we are  getting entry in CreatedFiles and InvitedFiles.It has to be in created Files only.

**Comment by Chandra-Aicumen** [comment]
@0zAND1z , code is in the repo and almost a month.  When can we move to master

**Comment by 0zAND1z** [comment]
@Chandra-Aicumen  can you please furnish the commit code to answer this question?  Thanks.

**Comment by its-VSP** [comment]
Under current stable version of file API this has been handling, so closing the issue
