### ISSUE TITLE
Edge case checklist for dashboard

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#108]
child to #105

@AchalaSB to list all the potential test cases based on the features available in the Dashboard.

**Comment by its-VSP** [comment]
@0zAND1z Can you plz elaborate on this?

**Comment by 0zAND1z** [comment]
Hi @its-VSP - Basically, the links in the dashboard have some expected actions to fulfil. You will help Achala list use cases that can expect a certain behaviour for each one of these button / link.

Hope this helps ;)

**Comment by its-VSP** [comment]
We need to re-open this issue in JIRA, if needed
