### ISSUE TITLE
Benchmark profilers for Data API

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#116]
child to #36

@its-VSP , please ensure to apply timers to measure the addition / removal of an entry in both the data stores, starting from _sending the entry object to the function_ to _receiving a hash_.

Timer results must be reported as specified under the parent EPIC #36.

**Comment by 0zAND1z** [comment]
@its-VSP info for you  on profiling: https://nodejs.org/en/docs/guides/simple-profiling/

**Comment by its-VSP** [comment]
We should have re-open this issue in JIRA , so closing this issue
