### ISSUE TITLE
Replacing drop with truncate in Data-API

### ISSUE THREAD

**Issue by its-VSP** [KIPFoundation/kfs#127]
Technically we can't delete/drop a store from KFS. That is the reason we are replacing dropping a store with truncating a store.

**Comment by its-VSP** [comment]
Q : What do you mean by truncating a store?
A : Truncating a store means flushing all the data within a store or emptying a store , where store still exists for crud operations.

**Comment by 0zAND1z** [comment]
Hi @its-VSP , does the flushing essentially remove the data or just the pointer to the latest state ?
Can you please provide clarity for the same? Thanks.

**Comment by its-VSP** [comment]
as data is immutable in kfs. its just the pointer to latest state.
But we can't track earlier state of store once flushed.

**Comment by its-VSP** [comment]
We reverted back to drop only , after implementing truncate functionality since mis-took the functionality laid down under drop earlier and no point in working on it, so closing it!
