### ISSUE TITLE
Bug in remove and add functionality in nested folder of depth 3

### ISSUE THREAD

**Issue by its-VSP** [KIPFoundation/kfs#129]

**Comment by its-VSP** [comment]
Adding file to the updated folder(second operation) under uploading folder (first operation) by benefactor to be fixed
And in above context removing the file ie., added using /upload/update can be removed by owner using /RemoveFileFolder.

**Comment by AchalaSB** [comment]
@akshitababel fix the issue in remove functionality when benefactor tries to  remove file from /updatefolder (like should get message `Permission Denied`)

**Comment by akshitababel** [comment]
@AchalaSB Ya he is getting message of "Permission Denied", if a benefactor try to remove a file

**Comment by 0zAND1z** [comment]
@its-VSP , if this bug is now resolved, can you please move it to REVIEW? Thanks.
