### ISSUE TITLE
Remove Folder

### ISSUE THREAD

**Issue by akshitababel** [KIPFoundation/kfs#130]

**Comment by 0zAND1z** [comment]
@akshitababel is working on supporting the REMOVE operations for app IDs / folders under an App ID.

**Comment by 0zAND1z** [comment]
Hi @its-VSP , if you think the code is now feature complete - can you go ahead & move this to REVIEW?

**Comment by its-VSP** [comment]
As current explorer is supporting removing folder and this has been tracked in JIRA , closing this issue
