### ISSUE TITLE
Bug in removing kvstore value in DATA API

### ISSUE THREAD

**Issue by AchalaSB** [KIPFoundation/kfs#132]
Context: Trying to remove key which is not existing in KV store
Expected Output : Key with <provided_key> not exists
Actual Output (BUG) : Entry Deleted.
@AchalaSB am i right?

**Comment by AchalaSB** [comment]
Should get "Entry Deleted" message only when it tries remove existed entries

**Comment by its-VSP** [comment]
I have fixed this and currently we migrated to JIRA , closing issue here
