### ISSUE TITLE
Fetch an empty store- Data API

### ISSUE THREAD

**Issue by AchalaSB** [KIPFoundation/kfs#133]
Expected output: Empty array
Actual output: "error": "Error: Database '/orbitdb/DB_Address' doesn't exist!"

**Comment by its-VSP** [comment]
To be elaborated :
Once the store has been created and very next you try to fetch store without adding any data into it, it should give empty array.

@AchalaSB This won't be the case 
if you use full address ie., /orbitdb/<store_hash>/<store_name

**Comment by AchalaSB** [comment]
@its-VSP yes, for the route  `/kfs-data-api/fetch/{address}/name` it's giving an empty array, but if I use same route  for the database which contain some entry  its not fetching all entries (giving an empty array)
