### ISSUE TITLE
Support Dynamic Changes to Secure Enclave

### ISSUE THREAD

**Issue by cattitude** [KIPFoundation/kfs#15]
child to #22

1. Secure enclave mapping of addresses
2. Push & Pop
3. Dynamic lookup of sender during store & retrieve
4. Dynamic lookup of receiver pub key based on Metamask

**Comment by kggp1995** [comment]
1. Silo based enclave v/s Global enclave thought @akshitababel ?

**Comment by kggp1995** [comment]
![image](https://user-images.githubusercontent.com/11145839/47698041-bac95680-dc33-11e8-90f3-a17013b321a5.png)

@akshitababel here is a good start with ordered priorities, from top to the bottom.

**Comment by kggp1995** [comment]
child to #22

**Comment by kggp1995** [comment]
child of #22

**Comment by kggp1995** [comment]
child to #22
