### ISSUE TITLE
Change of response code when replication is not happening

### ISSUE THREAD

**Issue by its-VSP** [KIPFoundation/kfs#166]
Currently when there is any file or folder is getting  uploaded but not replicated , API is sending response as 500( means Server side error) which cannot be handled by client.

**Acceptance Criteria to @akshitababel :**
Update the API code for the relevant _write based functions_ wherein the content is added to the networks with the hash returned, but the replication in the ipfs-cluster does not succeed properly with HTTP ERROR CODE 202 in the response header.

**Comment by its-VSP** [comment]
My suggestion is to use status code as 409 only because it is the conflict within server / env only.

**Comment by its-VSP** [comment]
@0zAND1z What you say?

**Comment by 0zAND1z** [comment]
Let's settle down with 202 (based on the [wiki list](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), this is the most suitable):

> 202 Accepted
>     The request has been accepted for processing, but the processing has not been completed. The request might or might not be eventually acted upon, and may be disallowed when processing occurs.[11]

**Comment by its-VSP** [comment]
Should be changed in both cases :  Uploading(pinning the file) and Removing (unpinning the file)

**Comment by its-VSP** [comment]
@0zAND1z 
It needs to be changed right?
when this is under done?

**Comment by its-VSP** [comment]
@0zAND1z @akshitababel 
And for when appID already exists , the response code set was 409 which again cannot be handled by client.

**Comment by 0zAND1z** [comment]
Thanks Sai, Noted. We will  re-open this to Inbox/Backlog.

**Comment by 0zAND1z** [comment]
Hey @its-VSP & @akshitababel  , please check the acceptance criteria & let me know if this is good enough.

**Comment by its-VSP** [comment]
Perfect!

**Comment by 0zAND1z** [comment]
@its-VSP & @AchalaSB  - can you confirm once this passing  QA?

**Comment by its-VSP** [comment]
@0zAND1z We Need input from @akshitababel whether she implemented this and pushed the same,  for me to consume and @AchalaSB to test
