### ISSUE TITLE
DIAUTH WORKFLOW

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#170]
**User Scenario 1:** A user who is new to the platform plans to create a new account and associate a minimum of one social identity.

**User Scenario 2:** A user with an already diAuth'ed account wishes to sign-in to an application requiring specific Auth Sources that are already verified. 

**User Scenario 3:** A user with an already diAuth'ed account wants to sign-in to an application requiring more Auth Sources that are yet to be verified by the user.

**Comment by its-VSP** [comment]
As this moved to JIRA , closing this issue
