### ISSUE TITLE
KFS Swarm Proxy Bridging

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#2]
**Problem Definition:**
A file from Swarm A must be accessed by an application running on Swarm B.

Storing the file again in Swarm B must be ignored(due to duplication, unwanted redundancy, lack of maintainability); hence a new mechanism is needed to bridge two Swarms for file/data access without diminishing the security features of KFS.

**Comment by kggp1995** [comment]
@akshitababel , can you update the findings on the `SwarmKey()` & `libp2p.PrivateNetwork`?

**Comment by kggp1995** [comment]
Referring to this: https://github.com/ipfs/go-ipfs/blob/672591972cfd3d3b180637822dc7f5e1dbbcf08d/repo/fsrepo/fsrepo.go#L68

**Comment by 0zAND1z** [comment]
This thread will be closed for now. 
In the future, it is planned to be re-assigned to @rahullenkala for long-term roadmap. 

Thanks to everybody involved!
