### ISSUE TITLE
Web diApp - UX Support  for update operations

### ISSUE THREAD

**Issue by cattitude** [KIPFoundation/kfs#21]
WRITE SCENARIO:
1. Allow user to check / uncheck if the data can be read-only OR read+write
2. Push the payload along with a code matching the selected type of operation
3. Map the user provided custom name to the App ID in case of RW. 
4. Else map the user provided custom file name to KFS File ID, in case of R.

READ SCENARIO:
1. Intended recipient can only access or read the data if the creator checked the read-only

UPDATE SCENARIO:
1. Intended recipient can access & write new data into the App ID.

**Comment by 1074Prasanth** [comment]
What is the difference between App id and KFS File id?

**Comment by ayushgupta0610** [comment]
88bbd52d30e6a3ea270048a0dab2cff885fdd1a3
