### ISSUE TITLE
Constant File ID per user

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#29]
child to #22
depends on #81
1. Hash must not change if the user uploads / updates same data/file for multiple times, versus changes to recipients.

**Comment by kggp1995** [comment]
**Challenge:**
Same file contents shared between disparate users are creating redundant encrypted objects on KFS, bloating the storage and limiting capacity.

**Current Strategy:**
Same files have different hashes / file IDs for different sets of senders and recipients

**Proposed Approaches:**
1. Establish a mapping: `Entitlement(FileID => SharedKey[])` to record multiple disparate access to separate users
2.

**Comment by cattitude** [comment]
Lack of de-duplication of encrypted payloads is the cause. Need a non-weak system (no permission , no authentication) to access info as a beneficiary

**Comment by 0zAND1z** [comment]
@chiragg6  - please document all the potential edge cases with @akshitababel .
Patch the commit & test for the same.
