### ISSUE TITLE
POST API - XML+JSON Parser & Renderer

### ISSUE THREAD

**Issue by cattitude** [KIPFoundation/kfs#30]
child to #28
1. We need an HTML Form Data -> XML converter.

**Comment by kggp1995** [comment]
@1074Prasanth , here is a good start: https://stackoverflow.com/questions/6066837/how-to-write-data-from-form-in-html-to-xml-with-javascript

**Comment by kggp1995** [comment]
List of addendums:
- [ ] Name , Age etc
- [ ] Owner of doc
- [ ] Intended user (for agencies)

**Comment by kggp1995** [comment]
@1074Prasanth does this work? https://stackoverflow.com/questions/45888863/how-can-we-save-html-form-data-into-xml-format-using-javascript-or-jquery

**Comment by ayushgupta0610** [comment]
Commit for the same: aaa7928cda9c34623bc7f57995ba9304b71d1135
