### ISSUE TITLE
AppID based XML data manager

### ISSUE THREAD

**Issue by cattitude** [KIPFoundation/kfs#33]
child to #28
1. Push the intended XML file as the latest state of the app data space.

2. View of audit trail

3. Direct access as a content / data object in byte stream

**Comment by ayushgupta0610** [comment]
Commit for the same: aaa7928cda9c34623bc7f57995ba9304b71d1135

**Comment by ayushgupta0610** [comment]
ce504d19511b408a051ce2f3400490a46fea7a68
