### ISSUE TITLE
KFS Action Diagram

### ISSUE THREAD

**Issue by praveennune** [KIPFoundation/kfs#4]
child to #50
@akshitababel Can you pls. create KFS diagrams depicting the layers and calls between the system. The swam key and the encryption should come out well enough for a first timer to get good understanding of KFS. We can do several internal reviews to finalize the initial draft.

**Comment by kggp1995** [comment]
@praveennune , let's close this tomorrow.
An early version with a common set of goals we had set back in 2017..  should be a good start!
