### ISSUE TITLE
HD Video File Streaming

### ISSUE THREAD

**Issue by cattitude** [KIPFoundation/kfs#42]
How far are we from live streaming videos in:
- [x] 720p
- [ ] 1080p
- [x] 4K

Check support for these file types:
- [ ] mkv
- [x] mp4
- [ ] avi
- [x] mov
- [ ] flv

**Comment by kggp1995** [comment]
@akshitababel just a quick comment on this will help.

**Comment by akshitababel** [comment]
I think I need to test this with one one example each.

**Comment by cattitude** [comment]
As per @its-VSP  -`mkv`did not render. Will file it as a bug tomorrow so that @akshitababel can find resolution.

**Comment by its-VSP** [comment]
Working/supporting video extension:
.mp4
not working video extension :
.mov 
.fla
.avi
.mkv
