### ISSUE TITLE
NESTED-FOLDERS

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#55]
# **Acceptance Criteria:**

## **1. Web Explorer must facilitate user to upload a nested folder comprising of files or folders or both:**

**Upload Screen:**
     - Facilitate upload by 2 modes: `browsing` AND `drag-and-drop`

## **2. Mobile Explorer must facilitate user to upload a nested folder comprising of files or folders or both:**

**Nuget:**
     - Facilitate upload by adding more functions for app developers to call

**App:**
     - Use the updated nuget with nested folder support & allow users to upload nested folders.

## **3. FILE API must support upload functionality for nested folders comprising of files or folders or both:**

**Constraints:**
     - Ensure to support nested folder upload without necessarily hosting it on the client

**Comment by its-VSP** [comment]
We have this been supported in current stable version of FILE-API , closing this issue
