### ISSUE TITLE
Unable to render non-mp4 videos

### ISSUE THREAD

**Issue by cattitude** [KIPFoundation/kfs#56]

**Comment by cattitude** [comment]
As confirmed by @its-VSP , we are not able to render the following video formats:
- [ ] mkv
- [ ] avi

**Comment by cattitude** [comment]
@akshitababel can we fix this from the API side?

**Comment by cattitude** [comment]
@akshitababel , if you have figured out a stable approach to this rendering bug, we can move this to **In Progress**

**Comment by cattitude** [comment]
@its-VSP did you check? Can you confirm if this is valid for the merge today?

**Comment by its-VSP** [comment]
@cattitude
did you patched the code/commit that solves this bug?

**Comment by cattitude** [comment]
@akshitababel Is the bug fixed & patched at server? 
If not patched yet, please take help from @chiragg6 .

Hi @its-VSP , I thought we patched this already.
Please wait for the patch & confirm if the bug is fixed.
