### ISSUE TITLE
Standard User Web Application

### ISSUE THREAD

**Issue by cattitude** [KIPFoundation/kfs#60]
child to #59 
A typical user interface on web to:
1. CRUD individual files
2. Create App IDs
3. Read App ID data
4. Expose all the owned individual files, and App ID folders in an explorer fashion

**Comment by ayushgupta0610** [comment]
@cattitude What we have as KFS web demo does exactly the same, right?

**Comment by its-VSP** [comment]
@cattitude 
let me know whether we are showcasing folder support for this release?
If so , that is needed to add in Demo-UI
