### ISSUE TITLE
KFS MOBILE APP

### ISSUE THREAD

**Issue by mosinms7711** [KIPFoundation/kfs#61]
EPIC to monitor progress of the KFS Mobile Explorer App (Both iOS and Android builds):

1. **Screens / Design:** - Design approaches similar to famous public cloud apps
2. **Upload File to the app:** - Picker must be provisioned when the user wants to upload a file from the mobile to KFS. 
3. **Create folders in the app:** - User must be able to create a new folder (a new App ID) by specifying the name & the tree location.
4. **Read File from the app:** - The app must be able to render basic file types such as Images & Videos within the application.
5. **Share File from the app:** - The app must facilitate the user to share a file while uploading to 
KFS by specifying the address of the recipient.
6. **REMOVE folder from the app:** - The app must facilitate the entitled users to remove a folder. LIMITATION to remove folders is applicable if the folder is created through the app. Meaning, Support for REMOVE is not required for folders created from the app (Since the folder was not directly uploaded but created as an AppID  with files uploaded).

**Comment by its-VSP** [comment]
@cattitude @akshitababel 
Typically what we need is all the files/folders/appIDs owning by particular user (where smart contract is giving today)
Optional : if you could able to give type of the file, we can add x-factor(like thumbnails) to UI and surprise team so that users.

**Comment by Chandra-Aicumen** [comment]
@0zAND1z . This card is for both Mobile and Web. Web version testing is completed by @its-VSP.  Mobile testing pending by @mosinms7711 .  Should we plan mobile for future sprint?

**Comment by 0zAND1z** [comment]
@Chandra-Aicumen , this card was intended to be  MOBILE-ONLY since inception.

Not sure why the confusion? 🤔 

Anyways, we intend to preserve this for BETA-5. So the answer is yes.

**Comment by its-VSP** [comment]
we can re-open this feature in JIRA
