### ISSUE TITLE
API: Intricate CRUD support for files in folders of AppID using host path

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#62]
child to #22.
Follow the same approach as that of #54.

**Comment by 0zAND1z** [comment]
@its-VSP please collect the changes you need to prep for the KFS Web Explorer

**Comment by Chandra-Aicumen** [comment]
@0zAND1z , what do you mean by Host path?  Should we move to Beta-4 or future sprint?

**Comment by 0zAND1z** [comment]
Hi @Chandra-Aicumen ,  @akshitababel  had earlier developed a route that could allow folder upload, but with a severe limitation: THE API MUST BE HOSTED ON THE CLIENT. The API would then refer to the absolute path of the files and then store the folder. 


In any case, I request you to share the commit code to check if this can move to DONE (provided the commit exists in master). Thanks

**Comment by Chandra-Aicumen** [comment]
@0zAND1z , code commit is 1063f293f71ab24be40ffab133f45dbb463e29d8  and in repo not in master.

**Comment by 0zAND1z** [comment]
Hi @Chandra-Aicumen , I see the commit was made 3 days ago.. If @its-VSP can confirm that the tests are all OK, we can review it & close it today.

**Comment by its-VSP** [comment]
This been reviewed and demoed , closing this issue
