### ISSUE TITLE
DASHBOARD-REVAMP

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#68]
# **Acceptance Criteria:**

## **1. Dashboard must render the following screens & monitor the remote kfs process with the following parameters:**

**Status Page:**
     - Network Bandwidth usage (along with in / out traffic)
     - Storage consumption
     - Number of connected peers
     - Peer ID
     - Software version
     - Advanced info (Gateway URL, API URL, Peer Pub Key, Peer IDs for making the connection)

**Peers Page:**
     - Counter to reflect number of peers connected in the swarm
     - Table listing all the connected peers columnated as follow: `Peer ID | Addresses | Location (Flag)`

**Cluster Management Page:**
     - Display the Swarm Key
     - Provision to set the new swarm key
     - Provision to connect to a Peer (Peer ID provided by the user)

**Settings Page:**
     - Option to edit or reset the content of the config file, and reflect changes accordingly.

## **2. Dashboard must support login and logout.**

**Login Page:**
     - Allow the designated admins to login with their Office 365 or Google for Work account
     - Facilitate a 2 factor authentication via diAuth
     - User must be redirected to _Status Page_, allowed to view/control the above pages _only_ after a successful login.

**User Story - Logout:**
     - Facilitate a user logout
     - Redirect to login page after successful logout.

**Comment by its-VSP** [comment]
As this project is been revamped, reviewed and demoed, so closing the issue
