### ISSUE TITLE
Edge case checklist - DATA API Permissioning

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#76]
depends on #63

Documentation to test the abilities of Permissioning in the DATA API:

- [ ]  Social engineering 
- [ ] Trace a public key

**Comment by 0zAND1z** [comment]
@0zAND1z will detail this.
@its-VSP will provide for the  technicalities.

**Comment by its-VSP** [comment]
One Edge case for access control on store is 
"Every user in network (ie., every node has same swarm) can able to read/view/fetch the entries in store".

**Comment by Chandra-Aicumen** [comment]
@0zAND1z , there are no tasks to be completed by tech team, is it a pure doc work ? Does this need a milestone?

**Comment by 0zAND1z** [comment]
Hi @Chandra-Aicumen , this is a readiness exercise, to understand how to protect our system. This goes in parallel to the dev. progress made on the DATA API. I would say yes, this needs to be part of the corresponding milestone.

In the future, I will try to consolidate these into one card to avoid any confusion.

**Comment by 0zAND1z** [comment]
Since @AchalaSB is already documenting the test cases for the Data API, I would like to assign  this to her.

**Comment by its-VSP** [comment]
We can re-open this issue, once we started again with DATA-API
