### ISSUE TITLE
API Rate Limit - All requests grouped per IP Address

### ISSUE THREAD

**Issue by akshitababel** [KIPFoundation/kfs#82]
child to #36
**ACCEPTANCE CRITERA:** 
1. Set the ceiling rate per minute. Host the API.
2. Make repeated calls to a route being monitored by its Physical Address
3. Observe the API call denied service at n(ceil + 1)

**Comment by 0zAND1z** [comment]
@chiragg6 will test the API rate limiting from multiple clients & confirm the acceptance criteria. 

@akshitababel please patch the commits.
