### ISSUE TITLE
Failed to READ Subsequent WRITEs by benefactor

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#84]

**Comment by Chandra-Aicumen** [comment]
@0zAND1z , code is in the repo and almost a month.  When can we move to master

**Comment by 0zAND1z** [comment]
@Chandra-Aicumen , please furnish the commit code for the corresponding work item. Shall review this request upon the same. Thanks.

**Comment by its-VSP** [comment]
We can re-open this issue in JIRA, once we start working on DATA-API
