### ISSUE TITLE
Consistent View for KFS Web Explorer

### ISSUE THREAD

**Issue by its-VSP** [KIPFoundation/kfs#88]
child to #90
depends on #125

**Acceptance Criteria:**
1. Consistent HTML content & design elements
2. No need to revamp the theme. Just place the UI components.

**Comment by Chandra-Aicumen** [comment]
@its-VSP , when you will push the code?

**Comment by 0zAND1z** [comment]
Also, @its-VSP , so you have cards to the corresponding tasks?

Please do not forget to cite those card numbers while committing. Thanks.

**Comment by Chandra-Aicumen** [comment]
@its-VSP  will push code to repo 18th repo

**Comment by 0zAND1z** [comment]
@Chandra-Aicumen , do you mean on 18th of MAR?

**Comment by 0zAND1z** [comment]
Dev finished in S1, needs to reviewed along with #125
