### ISSUE TITLE
Async Push - integrating shell to cluster

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#91]
child to #85

**Comment by chiragg6** [comment]
commit 3feae892b407f934c3cf8ff626841207ab1f4e54

**Comment by Chandra-Aicumen** [comment]
@0zAND1z , code is in the repo and almost a month.  When can we move to master.

**Comment by 0zAND1z** [comment]
Hi @Chandra-Aicumen , the commit was made on 15 FEB as part of BETA-3 milestone.
@akshitababel could not make it to the code review session on 1 MAR as she said she was travelling.

**Comment by 0zAND1z** [comment]
We can close it today though, after the all-round testing by @its-VSP

**Comment by its-VSP** [comment]
As current stable version of KFS-FILE-API is supporting ipfs-cluster , closing this issue
