### ISSUE TITLE
Sull support for ipfs-api

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#92]

**Comment by its-VSP** [comment]
@0zAND1z 
This card has been created only because "ipfs-api" is deprecated and we decided to migrate data API to make use of  "ipfs-http-client"
But orbit-db doesn't support ipfs-http-client completely 
So this task/migration is not implemented.

**Comment by 0zAND1z** [comment]
CLOSING COMMENTS: Unable to implement to due to lack of compatibility.

@its-VSP please concur. Thanks.
