### ISSUE TITLE
Support Complete Remove Funtionality

### ISSUE THREAD

**Issue by its-VSP** [KIPFoundation/kfs#93]
Remove file in the explorer as well , when remove is triggered to the file within folder.

**Comment by its-VSP** [comment]
Once #94 got implemented , this context won't arise.

**Comment by Chandra-Aicumen** [comment]
@0zAND1z , code is in the repo and almost a month.  When can we move to master

**Comment by 0zAND1z** [comment]
@Chandra-Aicumen , please furnish the commit code to address this question. Thanks.

**Comment by Chandra-Aicumen** [comment]
@0zAND1z ,  commit code is 541891af7d05205143a44ac91eca34a838fb058c

**Comment by 0zAND1z** [comment]
Hi @Chandra-Aicumen , the commit was made on 6th of March & falls under the purview of this sprint's code review meeting. 

Hence as such, there has been no delay on the review. Please check & let me know if there is any confusion on this matter.
