### ISSUE TITLE
Stop listing the files of folder/appID in explorer

### ISSUE THREAD

**Issue by its-VSP** [KIPFoundation/kfs#94]
As Discussed! We shouldn't list the files of APPID in the explorer

**Comment by its-VSP** [comment]
Typically we can have another attribute to file structure in explorer like.,
{ .......,
  ........,
  ........,
   isRootFile : True/False
}

**Comment by Chandra-Aicumen** [comment]
@0zAND1z , code is in the repo and almost a month.  When can we move to master

**Comment by 0zAND1z** [comment]
The bug 94 was addressed by @akshitababel under the commit 541891af made on 6th of MAR. 

So, there is no case of delay in review as its under the BETA-4 schedule. We shall review today, as planned.
