### ISSUE TITLE
React Dashboard Migration

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#95]
child to #68

- Remove Redux components
- Migrate React-only UI components
- Data binding & Click-action w/ APIs

**Comment by Chandra-Aicumen** [comment]
@its-VSP  rendering issues open and will close it on 18th march

**Comment by 0zAND1z** [comment]
@its-VSP is closing this today as per the A.C.

**Comment by 0zAND1z** [comment]
Planned to review the code on FRI.

**Comment by 0zAND1z** [comment]
Also , testing to happen in parallel.

**Comment by its-VSP** [comment]
Dashboard is been already reviewed and demoed , closing the issue
