### ISSUE TITLE
Dashboard Login

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#96]
child to #68
- Build a login screen to allow admins to login via Office365 and Google for Work
- Manage the SSO Auth token and make a call to diAuth contract with the Notary hash of the token

**Comment by 0zAND1z** [comment]
@its-VSP : Find more info on SSO Auth here: https://docs.microsoft.com/en-us/outlook/add-ins/authenticate-a-user-with-an-identity-token

**Comment by Chandra-Aicumen** [comment]
@its-VSP  to review this and discuss the task breakdown with estimate.

**Comment by 0zAND1z** [comment]
@its-VSP , can you please let us know if having a separate "custom"  and "private" NPM package for diAuth will help you achieve point 2 in the description? happy to help you there if the answer is YES.

**Comment by 0zAND1z** [comment]
As per Sai's capacity, this user story will be planned for next milestone. 

@its-VSP , feel free to knock here & pick it up if you have any time left in this sprint, if at all.

**Comment by its-VSP** [comment]
As we are working on DIAUTH, until which we can't take this up, so we can re-open this issue in JIRA once DIAUTH is in place
