### ISSUE TITLE
DATA API: Swagger enhancement

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kfs#98]
1. Routes definition
2. Request body examples

**Comment by 0zAND1z** [comment]
@its-VSP , can you add more description to each route published in the swagger-docs along with example request body for each route?

**Comment by its-VSP** [comment]
Will do that on coming monday ie., 10/03/2019.

**Comment by its-VSP** [comment]
We can re-open this issue in JIRA, if needed
